apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    #name: myapp
    component: web
spec:
  containers:
  - name: client
    image: stephengrider/multi-client
    ports:
      - containerPort: 3000
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    

