# Base image
FROM node:16-alpine

# Work directory
WORKDIR /usr/app

# Copy package.json to work directory
COPY ./frontend/package.json .

# Run comands to install dependencies
#RUN npm install
RUN yarn install

# Copy all the rest files
COPY ./frontend .

# Default commando for the image
#CMD [ "npm", "run", "start" ]
CMD [ "yarn", "start" ]




