version: '3'
services:
  react-web:
    container_name: react-web
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules # WHen you DONT use : -> means that (PUT A BOOKMARK ON THE node_modules FOLDER)
      - ./frontend:/usr/app # WHen you  use : -> means that (MAP the folder into the '/usr/app' folder)

  react-web-tests:
    container_name: react-web-test
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
      #- .:/usr/app #you can use . to say the current diretory
    #command: ["npm", "run", "test"]
    command: [ "yarn", "test" ]
